# MoRA tutorial

### Obtain the pretrained MoRA embeddings for any given coordinates

In [1]:
import sys
sys.path.append('pretrained_distilled_model')

import torch
from distilled_model import *

In [2]:
path = 'pretrained_distilled_model/distilled_MoRA.pth'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

c = torch.randn(32, 2) # Represents a batch of 32 locations (lon/lat)

model = load(path, device=device) # Load the distilled model as a surrogate for MoRA.
model.eval()
with torch.no_grad():
    embeddings = model(c.double().to(device)).detach().cpu()

In [3]:
embeddings

tensor([[ 0.2140, -0.3666,  0.0373,  ..., -0.4862, -0.1022,  0.3038],
        [ 0.0947,  0.0328,  0.0611,  ...,  0.0261, -0.0424,  0.0335],
        [-0.4449, -0.2777,  0.3031,  ..., -0.2111,  0.2882, -0.1221],
        ...,
        [-0.2487, -0.0877, -0.0953,  ...,  0.0835, -0.0025,  0.1161],
        [-0.0308, -0.0631, -0.0632,  ..., -0.2152, -0.0851,  0.1166],
        [-0.0391,  0.0655,  0.0177,  ...,  0.0230, -0.0049,  0.0852]],
       dtype=torch.float64)

In [4]:
embeddings.shape

torch.Size([32, 128])

### Get nationwide region embeddings

In [5]:
# get the coordinates of H3 in china
import pandas as pd

h3 = pd.read_pickle('embeddings/lv6_h3_china.pkl')

In [6]:
h3.head()

                h3   longitude   latitude
0  8640e3cefffffff  104.057273  30.665787
1  86408859fffffff  108.937699  34.266360
2  864118b2fffffff  113.286798  23.134293
3  864118b27ffffff  113.348234  23.123088
4  864019627ffffff  106.515547  29.568050

In [7]:
coords = torch.tensor(h3[['longitude', 'latitude']].values, dtype=torch.float32)

In [8]:
model.eval()
with torch.no_grad():
    embeddings = model(coords.double().to(device)).detach().cpu()

In [9]:
df = pd.DataFrame({
    'h3': h3['h3'],
    'ebd': embeddings.tolist()  
})

In [10]:
df.head()

                h3                                                ebd
0  8640e3cefffffff  [1.1620392464508211, -3.7438002390874336, 3.15...
1  86408859fffffff  [-0.9566033935427498, -0.9551551676872991, 2.5...
2  864118b2fffffff  [1.2709229718788717, -2.081754681916461, 2.206...
3  864118b27ffffff  [1.3712669695323667, -2.0311940487648483, 2.21...
4  864019627ffffff  [1.4732372747132403, -3.6665060901014828, 2.90...