# Get nationwide region embeddings

## Distilled MoRA embeddings

In [1]:
import sys
sys.path.append('../pretrained_distilled_model')

import torch
from distilled_model import *

Load the distilled model as a surrogate for MoRA.

In [2]:
path = '../pretrained_distilled_model/distilled_MoRA.pth'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = load(path, device=device)

Load the H3 central coordinates.

In [3]:
import pandas as pd

h3 = pd.read_pickle('lv6_h3_china.pkl')

In [4]:
h3.head()

                h3   longitude   latitude
0  8640e3cefffffff  104.057273  30.665787
1  86408859fffffff  108.937699  34.266360
2  864118b2fffffff  113.286798  23.134293
3  864118b27ffffff  113.348234  23.123088
4  864019627ffffff  106.515547  29.568050

In [5]:
coords = torch.tensor(h3[['longitude', 'latitude']].values, dtype=torch.float32)
model.eval()
with torch.no_grad():
    embeddings = model(coords.double().to(device)).detach().cpu()

In [6]:
embeddings.shape

torch.Size([195574, 128])

In [7]:
df = pd.DataFrame({
    'h3': h3['h3'],
    'ebd': embeddings.tolist()  
})

In [8]:
df.head()

                h3                                                ebd
0  8640e3cefffffff  [1.1620392464508211, -3.7438002390874336, 3.15...
1  86408859fffffff  [-0.9566033935427498, -0.9551551676872991, 2.5...
2  864118b2fffffff  [1.2709229718788717, -2.081754681916461, 2.206...
3  864118b27ffffff  [1.3712669695323667, -2.0311940487648483, 2.21...
4  864019627ffffff  [1.4732372747132403, -3.6665060901014828, 2.90...

Save the embeddings for downstream validation.

In [9]:
# save the embeddings for downstream evaluation
df.to_pickle('distilled_MoRA.pkl')

## SatCLIP embeddings

To obtained pretrained **SatCLIP** embeddings, first install the repository.

In [ ]:
!rm -r sample_data .config # Empty current directory
!git clone https://github.com/microsoft/satclip.git . # Clone SatCLIP repository

Install required packages.

In [ ]:
!pip install lightning --quiet
!pip install rasterio --quiet
!pip install torchgeo --quiet

We choose a SatCLIP using a vit vision encoder and $L=40$ Legendre polynomials for spherical harmonics calculation in the location encoder for comparison.

In [ ]:
!wget 'https://satclip.z13.web.core.windows.net/satclip/satclip-vit16-l40.ckpt'

In [10]:
import sys
sys.path.append('./satclip')


import torch
from load import get_satclip

In [13]:
satclip_path = 'satclip-vit16-l40.ckpt'

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


satclip_model = get_satclip(satclip_path, device=device) # Only loads location encoder by default
satclip_model.eval()

h3 = pd.read_pickle('lv6_h3_china.pkl')
coords = torch.tensor(h3[['longitude', 'latitude']].values, dtype=torch.float32)

with torch.no_grad():
    satclip_embeddings  = satclip_model(coords.double().to(device)).detach().cpu()

using pretrained moco vit16

In [14]:
satclip_df = pd.DataFrame({
    'h3': h3['h3'],
    'ebd': satclip_embeddings.tolist()  
})

In [15]:
satclip_df.head(2)

                h3                                                ebd
0  8640e3cefffffff  [0.7885097337042274, 0.668696744529086, 3.8145...
1  86408859fffffff  [-0.7540319008796809, 1.9027509927487722, -2.1...

In [ ]:
# save the embeddings for downstream evaluation
satclip_df.to_pickle('satclip.pkl')

## GeoCLIP embeddings

First install the package.

In [ ]:
!pip install geoclip

In [1]:
from geoclip import LocationEncoder
import pandas as pd
import torch
import torch.nn as nn


# Automatically load pretrained weights
geoclip_model = LocationEncoder()
geoclip_model.eval()


h3 = pd.read_pickle('lv6_h3_china.pkl')
coords = torch.tensor(h3[['latitude', 'longitude']].values, dtype=torch.float32)  ## Notice that GeoCLIP requires input to be (lat, lon)


with torch.no_grad():
    geoclip_embeddings = geoclip_model(coords).detach().cpu()

In [3]:
geoclip_df = pd.DataFrame({
    'h3': h3['h3'],
    'ebd': geoclip_embeddings.tolist()  
})

In [4]:
geoclip_df.head(2)

                h3                                                ebd
0  8640e3cefffffff  [-0.02009962499141693, 0.0038699787110090256, ...
1  86408859fffffff  [0.004778123460710049, -0.005807604640722275, ...

In [ ]:
# save the embeddings for downstream evaluation
geoclip_df.to_pickle('geoclip.pkl')